description: "Configure networking"

variables: 
  use_legacy_templating: false
  mod_networking_dnsservers:
    - 8.8.8.8
    - 8.8.4.4

tasks:
  -
    name: "Generate /etc/network/interfaces"
    command: "fs:copy"
    sudo: true
    arguments:
        src: "@{{ mod_path }}/assets/interfaces.twig"
        dest: "/etc/network/interfaces"
    trigger: "Restart networking"

triggers:
    -
      name: "Restart networking"
      command: "shell:exec"
      sudo: true
      arguments:
          command-line: "ifdown eth0 && ifup eth0"
